name: Docs build and deploy
on:
  workflow_run:
    workflows: ["Generate Full and Docs Changelog"]
    types: [completed]
  workflow_dispatch:
  push:
    paths:
      - "docs/**"
      - "mkdocs.yml"
permissions:
  contents: write
jobs:
  deploy:
    if: ${{ github.event_name != 'workflow_run' || github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('pyproject.toml') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install MkDocs and plugins
        run: |
          python -m pip install --upgrade pip
          pip install \
            mkdocs-material \
            mkdocstrings[python] \
            mkdocs-literate-nav \
            mkdocs-section-index \
            pymdown-extensions

      - name: Build documentation
        run: mkdocs build

      - name: Deploy documentation
        if: |
          github.event_name == 'push' ||
          github.event_name == 'workflow_dispatch' ||
          (github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success')
        run: mkdocs gh-deploy --force
